In [2]:
import numpy as np

In [3]:
np.set_printoptions(suppress=True,linewidth=100,precision=2)

In [4]:
raw_loan_Data=np.genfromtxt("loan-data.csv",delimiter=";",skip_header=1,autostrip=True)
raw_loan_Data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

<h1>Checking for incomplete dataset</h1>

In [6]:
np.isnan(raw_loan_Data).sum()

88005

In [7]:
raw_loan_Data.shape

(10000, 14)

In [8]:
tempom_fill=np.nanmax(raw_loan_Data).round(2)+1
tempom_fill

68616520.0

In [9]:
temp_mean=np.nanmean(raw_loan_Data ,axis=0)
temp_mean

/var/folders/nf/75gt_dxj21l9f2b0qy87f9hc0000gn/T/ipykernel_34808/3832816736.py:1: RuntimeWarning: Mean of empty slice
  temp_mean=np.nanmean(raw_loan_Data ,axis=0)


array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [10]:
temprory_state=np.array([np.nanmin(raw_loan_Data,axis=0),temp_mean,np.nanmax(raw_loan_Data,axis=0)])
temprory_state

/var/folders/nf/75gt_dxj21l9f2b0qy87f9hc0000gn/T/ipykernel_34808/3611067071.py:1: RuntimeWarning: All-NaN slice encountered
  temprory_state=np.array([np.nanmin(raw_loan_Data,axis=0),temp_mean,np.nanmax(raw_loan_Data,axis=0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [343]:
colums_string=np.argwhere(np.isnan(temp_mean)).squeeze()
colums_string
np.argwhere(np.isnan(temp_mean)).squeeze()

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [12]:
columns_numeric=np.argwhere(np.isnan(temp_mean)==False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13])

In [13]:
loan_Data_strings=np.genfromtxt("loan-data.csv",
                                delimiter=";",
                                skip_header=1,
                                autostrip=True,
                                usecols=colums_string,
                                dtype=np.str_)
loan_Data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [14]:
loan_Data_numeric=np.genfromtxt("loan-data.csv",
                                delimiter=";",
                                skip_header=1,
                                autostrip=True,
                                usecols=columns_numeric,
                                filling_values=tempom_fill


                               )
loan_Data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [15]:
header_full=np.genfromtxt("loan-data.csv",
                          delimiter=";",
                          skip_footer=raw_loan_Data.shape[0],
                          dtype=np.str_)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [16]:
header_strings,header_numeric=header_full[colums_string],header_full[columns_numeric]

In [17]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [18]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

<h1>Creating a Check points</h1>

In [20]:
def checkpoints(filename,checkpoint_header,checkpoint_data):
    np.savez(filename,header=checkpoint_header,data=checkpoint_data)
    check_point_variable=np.load(filename+".npz")
    return(check_point_variable)

In [21]:
checkpoint_test=checkpoints("checkpoint-test",header_strings,loan_Data_strings)

In [22]:
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [23]:
np.array_equal(checkpoint_test['data'],loan_Data_strings)

True

In [24]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [25]:
header_strings[0]='issuse_date'

In [26]:
header_strings

array(['issuse_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [27]:
loan_Data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [28]:
np.unique(loan_Data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [29]:
loan_Data_strings[:,0]=np.chararray.strip(loan_Data_strings[:,0],"-15")

In [30]:
np.unique(loan_Data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [31]:
months=np.array(["",'Jan','Feb','Mar','Apr',"May",'Jun','Jul','Aug','Sep','Oct','Nov','Dec'])
months.size

13

In [32]:
for i in range(13):
    loan_Data_strings[:,0] = np.where(loan_Data_strings[:,0]==months[i],
                                      i,
                                    loan_Data_strings[:,0]
                                      )

In [33]:
np.unique(loan_Data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [34]:
header_strings

array(['issuse_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [35]:
np.unique(loan_Data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [36]:
status_bad=np.array(['',"Charged Off",'Default','Late (31-120 days)'])
status_bad.shape

(4,)

In [37]:
# for i in range(3):
#     loan_Data_strings[:,1]=np.where(loan_Data_strings[:,1]==status_bad[i],
#                                     0,
#                                     1
#                                     )

In [38]:
loan_Data_strings[:,1]=np.where(np.isin(loan_Data_strings[:,1],status_bad),0,1)

In [39]:
np.unique(loan_Data_strings[:,1])

array(['0', '1'], dtype='<U69')

In [40]:
header_strings

array(['issuse_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [41]:
np.unique(loan_Data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [42]:
loan_Data_strings[:,2]=np.chararray.strip(loan_Data_strings[:,2]," months")

In [43]:
np.unique(loan_Data_strings[:,2])

array(['', '36', '60'], dtype='<U69')

In [44]:
loan_Data_strings[:,2]=np.where(loan_Data_strings[:,2]=='',
                                60,
                                loan_Data_strings[:,2]
                                )
loan_Data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [45]:
np.unique(loan_Data_strings[:,2])

array(['36', '60'], dtype='<U69')

In [46]:
np.unique(loan_Data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [47]:
header_strings

array(['issuse_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [48]:
np.unique(loan_Data_strings[:,3])[1:]

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [49]:
for i in np.unique(loan_Data_strings[:,3])[1:]:
    loan_Data_strings[:,4]=np.where((loan_Data_strings[:,4]=='')&(loan_Data_strings[:,3]==i),
                                    i+'5',
                                    loan_Data_strings[:,4]
                                    )

In [50]:
np.unique(loan_Data_strings[:,4],return_counts=True,return_index=True)


(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([ 222,  102,   23,  190,   19,    1,   44,   21,   59,   33,    2,   11,    9,    0,    5,
          83,   10,   85,   30,   55,   15,   93,   76,    4,   16,   37,   34,   50,   86,    6,
          87,  208,  447, 1138, 1732,  178]),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

In [51]:
loan_Data_strings.size

80000

In [52]:
loan_Data_strings[:,4]=np.where(loan_Data_strings[:,4]=="","H1",loan_Data_strings[:,4])

In [53]:
np.unique(loan_Data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [54]:
loan_Data_strings=np.delete(loan_Data_strings,3,axis=1)

In [55]:
loan_Data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [56]:
header_strings=np.delete(header_strings,3)

In [57]:
header_strings[3]

'sub_grade'

In [58]:
loan_Data_strings[:,3].shape

(10000,)

In [59]:
keys=list(np.unique(loan_Data_strings[:,3]))
values=list(range(1,np.unique(loan_Data_strings[:,3]).shape[0]+1))

In [60]:
print(values)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]


In [61]:
print(keys)

['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2', 'G3', 'G4', 'G5', 'H1']


In [62]:
dict_sub_grade=dict(zip(keys,values))

In [63]:
print(dict_sub_grade)

{'A1': 1, 'A2': 2, 'A3': 3, 'A4': 4, 'A5': 5, 'B1': 6, 'B2': 7, 'B3': 8, 'B4': 9, 'B5': 10, 'C1': 11, 'C2': 12, 'C3': 13, 'C4': 14, 'C5': 15, 'D1': 16, 'D2': 17, 'D3': 18, 'D4': 19, 'D5': 20, 'E1': 21, 'E2': 22, 'E3': 23, 'E4': 24, 'E5': 25, 'F1': 26, 'F2': 27, 'F3': 28, 'F4': 29, 'F5': 30, 'G1': 31, 'G2': 32, 'G3': 33, 'G4': 34, 'G5': 35, 'H1': 36}


In [64]:
for i in np.unique(loan_Data_strings[:,3]):
    loan_Data_strings[:,3]=np.where(loan_Data_strings[:,3]==i,
                                    dict_sub_grade[i],
                                    loan_Data_strings[:,3]
                                    )

In [65]:
np.unique(loan_Data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [66]:
np.unique(loan_Data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [67]:
header_strings

array(['issuse_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [68]:
bad_verification_status=['','Not Verified']

In [69]:
# loan_Data_strings[:,4]=np.where(np.isin(loan_Data_strings[:,4],bad_verification_status),0,1 )
loan_Data_strings[:,4]=np.where((loan_Data_strings[:,4]==bad_verification_status[0])|(loan_Data_strings[:,4]==bad_verification_status[1]),0,1)

In [70]:
np.unique(loan_Data_strings[:,4])

array(['0', '1'], dtype='<U69')

In [71]:
loan_Data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [72]:
np.chararray.strip(loan_Data_strings[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [73]:
loan_Data_strings[:,5]=np.chararray.strip(loan_Data_strings[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [74]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [75]:
loan_Data_numeric[:,0].astype(dtype=np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249], dtype=int32)

In [76]:
loan_Data_strings[:,5].astype(dtype=np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249], dtype=int32)

In [77]:
np.array_equal(loan_Data_numeric[:,0].astype(dtype=np.int32),loan_Data_strings[:,5].astype(dtype=np.int32))

True

In [78]:
loan_Data_strings = np.delete(loan_Data_strings,5,axis=1)

In [79]:
loan_Data_strings

array([['5', '1', '36', '13', '1', 'CA'],
       ['0', '1', '36', '5', '1', 'NY'],
       ['9', '1', '36', '10', '1', 'PA'],
       ...,
       ['6', '1', '36', '5', '1', 'CA'],
       ['4', '1', '36', '17', '1', 'OH'],
       ['12', '1', '36', '4', '0', 'IL']], dtype='<U69')

In [80]:
loan_Data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [81]:
header_strings

array(['issuse_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [82]:
header_strings=np.delete(header_strings,5)

In [83]:
header_strings

array(['issuse_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [84]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [85]:
loan_Data_strings

array([['5', '1', '36', '13', '1', 'CA'],
       ['0', '1', '36', '5', '1', 'NY'],
       ['9', '1', '36', '10', '1', 'PA'],
       ...,
       ['6', '1', '36', '5', '1', 'CA'],
       ['4', '1', '36', '17', '1', 'OH'],
       ['12', '1', '36', '4', '0', 'IL']], dtype='<U69')

In [86]:
header_strings[5]="state_address"

In [87]:
header_strings

array(['issuse_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'state_address'],
      dtype='<U19')

In [88]:
np.unique(loan_Data_strings[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [89]:
states_name,states_count=np.unique(loan_Data_strings[:,5],return_counts=True)
state_count_in_order=np.argsort(-states_count)
states_name[state_count_in_order],states_count[state_count_in_order]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

In [90]:
np.argsort(-states_count)

array([ 5, 33, 42, 10,  0, 13, 30, 11, 37, 34, 21, 26, 44, 19,  4, 46, 18,  6, 23, 22, 14, 47,  7,
       41, 32,  2, 17, 36, 39, 16, 15, 35, 43,  3, 24, 29, 31, 48, 12, 38, 25,  9,  8, 49,  1, 28,
       40, 45, 27, 20])

In [91]:
loan_Data_strings[:,5]=np.where(loan_Data_strings[:,5]=="",
                                0,
                                loan_Data_strings[:,5]
                                )

In [92]:
state_west = np.array(['AK', 'AZ', 'CA', 'CO', 'HI', 'ID', 'MT', 'NV', 'NM', 'OR', 'UT', 'WA', 'WY'])
state_south = np.array(['AL', 'AR', 'FL', 'GA', 'KY', 'LA', 'MS', 'NC', 'SC', 'TN', 'TX', 'VA', 'WV',"DC","DE"])
state_middleeast = np.array([ 'MD', 'NJ', 'NY','MN','IL',"MI","Ne","ND","OH","SD","IL",'WI',"OK","IN","MO","NE"])
state_east = np.array(["PA",'KS','CT', 'MA', 'ME', 'NH', 'RI', 'VT',])

In [93]:
loan_Data_strings[:,5]=np.where(np.isin(loan_Data_strings[:,5],state_west),1,loan_Data_strings[:,5])
loan_Data_strings[:,5]=np.where(np.isin(loan_Data_strings[:,5],state_south),2,loan_Data_strings[:,5])
loan_Data_strings[:,5]=np.where(np.isin(loan_Data_strings[:,5],state_middleeast),3,loan_Data_strings[:,5])
loan_Data_strings[:,5]=np.where(np.isin(loan_Data_strings[:,5],state_east),4,loan_Data_strings[:,5])


In [94]:
np.unique(loan_Data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [95]:
loan_Data_strings= loan_Data_strings.astype(dtype=np.int32)

In [96]:
header_strings

array(['issuse_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'state_address'],
      dtype='<U19')

In [97]:
loan_Data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  3],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], dtype=int32)

In [98]:
check_point_string=checkpoints("Check-Point",header_strings,loan_Data_strings)

In [99]:
check_point_string["header"]

array(['issuse_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'state_address'],
      dtype='<U19')

In [100]:
check_point_string["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  3],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], dtype=int32)

In [101]:
np.array_equal(check_point_string["data"],loan_Data_strings)

True

In [102]:
loan_Data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  3],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], dtype=int32)

In [103]:
check_point_string["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  3],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], dtype=int32)

In [104]:
loan_Data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [105]:
np.isnan(loan_Data_numeric).sum()

0

In [106]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [107]:
temprory_state[:,columns_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [108]:
columns_numeric

array([ 0,  2,  4,  6,  7, 13])

In [109]:
loan_Data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [110]:
loan_Data_numeric[:,2]=np.where(loan_Data_numeric[:,2]==tempom_fill,
                                temprory_state[0,columns_numeric[2]],
                                loan_Data_numeric[:,2]
                                )

In [111]:
loan_Data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [112]:
temprory_state[0,columns_numeric[3]]

6.0

In [113]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [114]:
for i in [1,3,4,5]:
    loan_Data_numeric[:,i]=np.where(loan_Data_numeric[:,i]==tempom_fill,
                                temprory_state[2,columns_numeric[i]],
                                loan_Data_numeric[:,i]
                                )

In [115]:
loan_Data_numeric[:,1]

array([35000., 30000., 15000., ..., 10000., 35000., 10000.])

<h3>Exchange Rate</h3>

In [117]:
EUP_USD=np.genfromtxt("EUR-USD.csv",delimiter=",",skip_header=1,autostrip=True,usecols=3)

In [118]:
EUP_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [119]:
loan_Data_strings[:,0]

array([ 5,  0,  9, ...,  6,  4, 12], dtype=int32)

In [120]:
exchange_rate=loan_Data_strings[:,0]
for i in range(1,13):
    exchange_rate=np.where(exchange_rate==i,EUP_USD[i-1],exchange_rate)

In [121]:
exchange_rate.size

10000

In [122]:
for i in range(1,13):
    exchange_rate=np.where(exchange_rate==0,np.mean(EUP_USD),exchange_rate)

In [123]:
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [124]:
exchange_rate.shape

(10000,)

In [125]:
loan_Data_numeric.shape

(10000, 6)

In [126]:
exchange_rate=np.reshape(exchange_rate,(10000,1))

In [127]:
exchange_rate

array([[1.1 ],
       [1.11],
       [1.13],
       ...,
       [1.12],
       [1.11],
       [1.09]])

In [128]:
loan_Data_numeric=np.hstack((loan_Data_numeric,exchange_rate))

In [129]:
loan_Data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [130]:
header_numeric = np.concatenate((header_numeric,np.array(["exchange_rate"])))

In [131]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

<h1>From usd to eur</h1>

In [133]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [134]:
dolloar_Amount=np.array([1,2,4,5])

In [135]:
loan_Data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [136]:
for i in dolloar_Amount:
    loan_Data_numeric=np.hstack((loan_Data_numeric,np.reshape(loan_Data_numeric[:,i]/loan_Data_numeric[:,6],(10000,1))))

In [137]:
loan_Data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [138]:
header_Additonal=np.array([column_name +"_EUR" for column_name in header_numeric[dolloar_Amount] ])

In [139]:
header_Additonal

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [140]:
header_numeric=np.concatenate((header_numeric,header_Additonal))

In [141]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [142]:
header_numeric[dolloar_Amount]=np.array([column_name+"_USD" for column_name in header_numeric[dolloar_Amount]])

In [143]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [144]:
column_index_order=[0,1,7,2,8,3,4,9,5,10,6]

In [145]:
header_numeric=header_numeric[column_index_order]

In [146]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [147]:
loan_Data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [148]:
loan_Data_numeric=loan_Data_numeric[:,column_index_order]

In [149]:
loan_Data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

In [150]:
loan_Data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

In [151]:
header_numeric[5]

'int_rate'

In [152]:
loan_Data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [153]:
loan_Data_numeric[:,5]=loan_Data_numeric[:,5]/100

In [154]:
loan_Data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

In [155]:
checkpoint_numeric=checkpoints("Check-Point-Numeric",header_numeric,loan_Data_numeric)

In [156]:
checkpoint_numeric["header"]

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [157]:
checkpoint_numeric["data"]

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

<h1>Creating a complete dataset</h1>

In [159]:
check_point_string["data"].shape

(10000, 6)

In [160]:
checkpoint_numeric["data"].shape

(10000, 11)

In [161]:
loan_data=np.hstack((checkpoint_numeric["data"],check_point_string["data"]))

In [162]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        3.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [163]:
np.isnan(loan_data).sum()

0

In [164]:
header_full=np.concatenate((checkpoint_numeric["header"],check_point_string["header"]))

In [165]:
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issuse_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'state_address'],
      dtype='<U19')

In [166]:
loan_data=loan_data[np.argsort(loan_data[:,0])]

In [167]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        3.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [168]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [169]:
loan_data=np.vstack((header_full,loan_data))

In [170]:
loan_data

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'state_address'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '3.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [171]:
np.savetxt("Loan-Data-Preprocessed.csv",loan_data, fmt="%s", delimiter=",")